from typing import Dict, Any, Optional
import os
import datetime


class ReportGenerator:
    """Generate text reports and save logs.

    The generator accepts either an AnalysisContext-like object (with attributes)
    or a plain dict containing keys such as 'results', 'input_path', 'output_dir'.
    """

    def _get_attr(self, context: Any, name: str, default=None):
        if isinstance(context, dict):
            return context.get(name, default)
        return getattr(context, name, default)

    def generate_text_report(self, context: Dict[str, Any]) -> str:
        """Create a concise text report from a context or results dict and return it as a string."""
        results = self._get_attr(context, 'results', context)
        input_path = self._get_attr(context, 'input_path', None)
        output_dir = self._get_attr(context, 'output_dir', None)

        lines = []
        lines.append('=' * 80)
        header = f"GNSS Analysis Report - {datetime.datetime.utcnow().isoformat()}Z"
        lines.append(header)
        lines.append('=' * 80)
        if input_path:
            lines.append(f"Input file: {input_path}")
        if output_dir:
            lines.append(f"Output dir: {output_dir}")
        lines.append('')

        # Basic sections with safe lookups
        # 1) dCMC summary
        dcmc = results.get('dcmc', {}) if isinstance(results, dict) else {}
        total_dcmc_sats = len(dcmc)
        total_dcmc_combinations = sum(len(freqs) for freqs in dcmc.values()) if dcmc else 0
        lines.append(f"dCMC: satellites={total_dcmc_sats}, combinations={total_dcmc_combinations}")

        # 2) CCI/ROC
        roc = results.get('roc_model', {}) if isinstance(results, dict) else {}
        lines.append(f"ROC models: {len(roc)}")

        # 3) Corrected phases
        corrected = results.get('corrected_phase', {}) if isinstance(results, dict) else {}
        corrected_sats = len(corrected)
        corrected_entries = sum(len(freqs) for freqs in corrected.values()) if corrected else 0
        lines.append(f"Corrected phases: satellites={corrected_sats}, combos={corrected_entries}")

        # 4) Coarse error summary
        triple = results.get('triple_errors', {}) if isinstance(results, dict) else {}
        if triple:
            count_triple = sum(len(freqs) for freqs in triple.values())
            lines.append(f"Triple-median error entries: {count_triple}")

        # 5) ISB
        isb = results.get('isb_analysis', {}) if isinstance(results, dict) else {}
        if isb:
            lines.append(f"ISB mean: {isb.get('isb_mean', 'N/A')}, epochs: {len(isb.get('isb_epochs', []))}")

        # 6) Notes / meta
        meta = results.get('meta', {}) if isinstance(results, dict) else {}
        if meta:
            lines.append('Meta:')
            for k, v in meta.items():
                lines.append(f"  {k}: {v}")

        # Footer
        lines.append('')
        lines.append('Report generated by Android_GNSS_Analysis')
        lines.append('=' * 80)

        return '\n'.join(lines)

    def save_logs(self, log_type: str, content: str, output_dir: str, prefix: Optional[str] = None) -> str:
        """Save `content` into a log file under `output_dir` with a timestamped name.

        Returns the path to the written log file.
        """
        os.makedirs(output_dir, exist_ok=True)
        ts = datetime.datetime.utcnow().strftime('%Y%m%dT%H%M%SZ')
        if prefix:
            filename = f"{prefix}-{log_type}-{ts}.log"
        else:
            filename = f"{log_type}-{ts}.log"
        path = os.path.join(output_dir, filename)
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
        return path
